/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/nfbJmxsEKOv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import Header from "../header/page"
export default function Tourist() {
  const [fromDate, setFromDate] = useState(null)
  const [toDate, setToDate] = useState(null)
  return (<>
    <div className="w-full  mx-auto ">
      <Header />
      <div className="flex space-x-4 mt-6">
        <aside className="w-1/4">
          <nav className="space-y-2 ">
            <Button variant="ghost" className="w-full text-left hover:bg-blue-600 hover:underline">
              Flights
            </Button>
            <Button variant="ghost" className="w-full text-left hover:underline">
              Stays
            </Button>
            <Button variant="ghost" className="w-full text-left hover:underline">
              Cars
            </Button>
            <Button variant="ghost" className="w-full text-left hover:underline">
              Flight+Hotel
            </Button>
            <Button variant="ghost" className="w-full text-left hover:underline">
              Ask TRIP SINC
            </Button>
            <Button variant="ghost" className="w-full text-left hover:underline">
              Explore
            </Button>
            <Button variant="ghost" className="w-full text-left hover:underline">
              Flight Tracker
            </Button>
            <Button variant="ghost" className="w-full text-left hover:underline">
              Best Time to Travel
            </Button>
            <Button variant="ghost" className="w-full text-left hover:underline">
              TRIP SINC for Business
            </Button>
            <Button variant="ghost" className="w-full text-left hover:underline">
              Trips
            </Button>
          </nav>
        </aside>
        <main className="w-3/4 space-y-8">
          <section>
            <h1 className="text-3xl font-bold">Compare flights from 100s of sites.</h1>
            <p className="mt-4 text-muted-foreground">
              Trip Sinc helps you find the best deals on flights, hotels, and car rentals. We search hundreds of travel
              sites to help you find the lowest prices and the most convenient options for your trip.
            </p>
            <div className="flex items-center space-x-4 mt-4">
              <Select className="bg-green-400">
                <SelectTrigger aria-label="Return">
                  <SelectValue placeholder="Return" />
                </SelectTrigger>
                <SelectContent className="bg-green-400">
                  <SelectItem value="return">Two-way</SelectItem>
                  <SelectItem value="one-way">One-way</SelectItem>
                  <SelectItem value="multi-city">Multi-city</SelectItem>
                </SelectContent>
              </Select>
              <Select>
                <SelectTrigger aria-label="Passengers">
                  <SelectValue placeholder="1 adult" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1 adult</SelectItem>
                  <SelectItem value="2">2 adults</SelectItem>
                  <SelectItem value="3">3 adults</SelectItem>
                </SelectContent>
              </Select>
              <Select>
                <SelectTrigger aria-label="Class">
                  <SelectValue placeholder="Economy" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="economy">Economy</SelectItem>
                  <SelectItem value="business">Business</SelectItem>
                  <SelectItem value="first">First</SelectItem>
                </SelectContent>
              </Select>
              <Select>
                <SelectTrigger aria-label="Bags">
                  <SelectValue placeholder="0 bags" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="0">0 bags</SelectItem>
                  <SelectItem value="1">1 bag</SelectItem>
                  <SelectItem value="2">2 bags</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex items-center space-x-4" style={{ marginTop: '120px' }}>
              <Input placeholder="Calgary (YYC)" />
              <ShuffleIcon className="h-6 w-6" />
              <Input placeholder="To?" />
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="flex items-center space-x-2">
                    <CalendarIcon className="h-5 w-5" />
                    <span>{fromDate ? fromDate.toLocaleDateString() : "Mon 22/7"}</span>
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar mode="single" selected={fromDate} onSelect={setFromDate} />
                </PopoverContent>
              </Popover>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="flex items-center space-x-2">
                    <CalendarIcon className="h-5 w-5" />
                    <span>{toDate ? toDate.toLocaleDateString() : "Mon 29/7"}</span>
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar mode="single" selected={toDate} onSelect={setToDate} />
                </PopoverContent>
              </Popover>
              <Button variant="default">
                <SearchIcon className="h-5 w-5" />
              </Button>
            </div>
          </section>
        </main>
      </div>
    </div>
    </>
  );
}

function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function ShuffleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 18h1.4c1.3 0 2.5-.6 3.3-1.7l6.1-8.6c.7-1.1 2-1.7 3.3-1.7H22" />
      <path d="m18 2 4 4-4 4" />
      <path d="M2 6h1.9c1.5 0 2.9.9 3.6 2.2" />
      <path d="M22 18h-5.9c-1.3 0-2.6-.7-3.3-1.8l-.5-.8" />
      <path d="m18 14 4 4-4 4" />
    </svg>)
  );
}
